### ISSUE TITLE
Handle requests of different types that supersede each other

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#808] opened 2017-04-13 10:34 UTC
https://build.opensuse.org/request/show/487630 not sure how it does happened

**Comment by jberry-suse** [comment] 2017-04-18 05:06
I double checked code and the appropriate conditions are there. Hmm, I'll have to play around with the specific request.

**Comment by jberry-suse** [comment] 2017-05-03 02:43
[request_splitter.py (line 116)](https://github.com/openSUSE/osc-plugin-factory/blob/9ea9a50c352e1d95db5e7c7738107274c0482f95/osclib/request_splitter.py#L116):

```python
ring = self.ring_get(target_package)
if ring:
    target.set('ring', ring)
elif request.find('./action').get('type') == 'delete':
    # Delete requests should always be considered in a ring.
    target.set('ring', 'delete')
```

To confirm further I ran the following code.

```python
from osc.core import get_request
from lxml import etree as ET
splitter = RequestSplitter(api, [ET.fromstring(get_request(api.apiurl, str(487630)).to_str())], in_ring=True)
splitter.split()
print(splitter.other)
print(sorted(splitter.grouped.keys()))
```

After `supplement()` it included `ring="delete"` and post `split()` it was spaced in the `splitter.grouped` correctly. If `in_ring` was set to `False` then it was placed in `splitter.other` which is not processed by `adi`. I am rather curious what magic caused this to occur.

Still intriguing. Have we see this occur again? If not then lets close this until we have more information.

**Comment by DimStar77** [comment] 2017-05-08 08:53
https://build.opensuse.org/request/show/491374 is a case of a delete request that went into an adi staging again (see the history... I removed it from that group)

**Comment by jberry-suse** [comment] 2017-05-08 16:14
Did you see output, was it superseded to that location or something like that?

**Comment by jberry-suse** [comment] 2017-05-08 16:16
Unfortunately, the staging must have been deleted and re-created as the meta history does not include the request in equestion.

**Comment by jberry-suse** [comment] 2017-05-09 03:28
Next time one is encountered please check the meta history to see if a request for the same package was previously staged there and the delete superseded it.

Likely the following line from `StagingAPI` should be changed.
```python
if action.get('type') in ['submit', 'delete'] and ...
```
to
```python
if action.get('type') == 'submit' and ...
```

Since it likely does not make sense for `delete` to supersede. If anything the correct course of action would be to `unselect` the `submit` request and then stage the `delete`. The code could be modified to do so, but that assumes that behavior is desired in that a change in request type should always replace the previous.

Instead it may make sense to add to ignore list pending human review the same way leap multi-source workflow functions or decline with a message requesting that the other request is revoked first to confirm intent.

**Comment by jberry-suse** [comment] 2017-05-17 01:29
Confirmed that this sort of thing does in fact happen. An example in the reverse which is easy to track since letter staging leave a history.

The requests in question:

- [**Submit** package openSUSE:Factory / freenx-client](https://build.opensuse.org/request/show/479059) `2 months ago`
- [**Delete** package openSUSE:Factory / freenx-client](https://build.opensuse.org/request/show/495393) `10 hours ago`

Order of events:

- **submit** declined `2 months ago`
- **delete** correctly staged in `E` `8 hours ago`
- **submit** reopened `5 hours ago`
- **submit** supersedes **delete** `3 hours ago`

The supersede logic has remained the same for a while in that it always considers the unstaged request against the staged request. I would image the reverse of this has been happening to cause the staging of deletes in adi. Meaning that a non-ring submit is staged in adi then superseded by a delete.

My proposal for changing this behavior to avoid the issue is as follows.

- maintain supersede logic for deciding who wins, and decline + unstage the request to be superseded
- if types do not match then skip out of logic so the new request will be considered a fresh request to stage via normal rules

Alternatively, when the request types do not match the non-staged request could be ignored with a message to indicate the issue and wait for human review.

**Closed** 2017-06-01 08:39 UTC
