### ISSUE TITLE
leaper: handle delete requests

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#975] opened 2017-06-28 09:33 UTC
leaper needs to also handle delete request, eg stating whether it's a sle package or whether other packages depend on the package at hand.

e.g. https://build.opensuse.org/request/show/501716

**Comment by jberry-suse** [comment] 2017-06-28 12:17
Same as #943, but includes SLE note. By SLE I assume you mean always decline if in SLE and origin is SLE, otherwise suggest using SLE version?

**Comment by lnussel** [comment] 2017-06-29 15:31
maybe declining right away i also an option, yes. at the least having the information there would be helpful already. otherwise I agree, duplicate.

**Comment by jberry-suse** [comment] 2017-06-29 18:53
repochecker has this sort of check although it is limited to build time dependencies (ie I left TODO in code to improve the way I did to `cleanup_rings` to include runtime). The one complication to declining is that a delete request may only be valid once staged with other requests, but of course may miss if not in same stagings. My current plan was to present the information in leaper and then have repochecker include the full check in addition to checking any packages in main project that are not included in staging. That way it allows for groups of requests that make a delete ok while still attempting to protect against non-grouped packages.

**Comment by jberry-suse** [comment] 2017-07-18 06:10
Closing since we agree this is duplicate of #943 and #277 should cover any remaining bases.

**Closed by jberry-suse** 2017-07-18 06:10 UTC
